# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - name: Deleting old publication
        run: |
          mkdir build
          git worktree prune
          rm -rf .git/worktrees/build/
      
      - name: Checking out gh-pages branch into build
        run: git worktree add -B gh-pages build gh-pages
      
      - name: Removing existing files from build folder
        run: rm -rf build/*

      - name: Generating static site
        run: npm run build

      - name: Updating gh-pages branch
        run: cd build && git add --all && git commit -m "Publishing to gh-pages"

      - name: Publish
        run: git push -f origin gh-pages
